version: "2"
services:
  app:
    command: ["npm", "run-script", "docker-start"]
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"            
    # network_mode: host
    links:
      - mongo      
          
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ~/data:/data/db
    ports:
      - "27017:27017"